/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RaisinEditor {
    }
}
declare global {
    interface HTMLRaisinEditorElement extends Components.RaisinEditor, HTMLStencilElement {
    }
    var HTMLRaisinEditorElement: {
        prototype: HTMLRaisinEditorElement;
        new (): HTMLRaisinEditorElement;
    };
    interface HTMLElementTagNameMap {
        "raisin-editor": HTMLRaisinEditorElement;
    }
}
declare namespace LocalJSX {
    interface RaisinEditor {
    }
    interface IntrinsicElements {
        "raisin-editor": RaisinEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "raisin-editor": LocalJSX.RaisinEditor & JSXBase.HTMLAttributes<HTMLRaisinEditorElement>;
        }
    }
}
