/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { VNode } from "@stencil/core";
export namespace Components {
    interface HasSlots {
    }
    interface RaisinEditor {
    }
    interface StencilView {
        "view": VNode | VNode[];
    }
}
declare global {
    interface HTMLHasSlotsElement extends Components.HasSlots, HTMLStencilElement {
    }
    var HTMLHasSlotsElement: {
        prototype: HTMLHasSlotsElement;
        new (): HTMLHasSlotsElement;
    };
    interface HTMLRaisinEditorElement extends Components.RaisinEditor, HTMLStencilElement {
    }
    var HTMLRaisinEditorElement: {
        prototype: HTMLRaisinEditorElement;
        new (): HTMLRaisinEditorElement;
    };
    interface HTMLStencilViewElement extends Components.StencilView, HTMLStencilElement {
    }
    var HTMLStencilViewElement: {
        prototype: HTMLStencilViewElement;
        new (): HTMLStencilViewElement;
    };
    interface HTMLElementTagNameMap {
        "has-slots": HTMLHasSlotsElement;
        "raisin-editor": HTMLRaisinEditorElement;
        "stencil-view": HTMLStencilViewElement;
    }
}
declare namespace LocalJSX {
    interface HasSlots {
    }
    interface RaisinEditor {
    }
    interface StencilView {
        "view"?: VNode | VNode[];
    }
    interface IntrinsicElements {
        "has-slots": HasSlots;
        "raisin-editor": RaisinEditor;
        "stencil-view": StencilView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "has-slots": LocalJSX.HasSlots & JSXBase.HTMLAttributes<HTMLHasSlotsElement>;
            "raisin-editor": LocalJSX.RaisinEditor & JSXBase.HTMLAttributes<HTMLRaisinEditorElement>;
            "stencil-view": LocalJSX.StencilView & JSXBase.HTMLAttributes<HTMLStencilViewElement>;
        }
    }
}
