name: Validate PR

on:
  pull_request:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup 20.x
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.x

      - uses: bahmutov/npm-install@v1
        with:
          # We can't use our lockfile, because of platform-specific optional dependencies in Vite
          # https://github.com/npm/cli/issues/4828
          # Will create errors like: `Error: Cannot find module @rollup/rollup-linux-x64-gnu.`
          useLockFile: false

      - name: Lint (via Turbo)
        run: npm run lint

      - name: Build (via Turbo)
        run: npm run build

      - name: Test (via Turbo)
        run: npm test
        env:
          # For Playwright -- Firefox is unable to launch if the $HOME folder isn't owned by the current user. 
          HOME: /root

        # Uploads the playwright test results folder, this has HTML and video of failures in it
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          # If nothing is found, then we have a configuration error
          # The reports should always exist, even on success
          if-no-files-found: error
          # Bring other test results into this one artefact (if other packages get them)
          path: |
            packages/react/.end2end-report
